name: crimson_app
description: A Weverse-style fan community application.
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core dependencies
  http: ^1.1.0
  cupertino_icons: ^1.0.2

  # ✅ Add Firebase dependencies
  firebase_core: ^3.4.0
  firebase_auth: ^5.3.1
  
  # 👇 CORRECTED: PROVIDER MUST BE HERE, UNDER dependencies:
  provider: ^6.0.5 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/avatars/
    - lib/data/mock_feed_data.json
    - crimson_backend/data/mockMembers.js