// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
//await Firebase.initializeApp(
  // options: DefaultFirebaseOptions.currentPlatform,
/// );
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC22oNgNbYqUu3ldzduehMmQ2t3dS5ZHt4',
    appId: '1:1083009137937:web:bc16a12ce33f5faff520b0',
    messagingSenderId: '1083009137937',
    projectId: 'flutterauthentication-ae1d0',
    authDomain: 'flutterauthentication-ae1d0.firebaseapp.com',
    storageBucket: 'flutterauthentication-ae1d0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLA0nAmxLmY0D79AinjiiPmgng150j2VY',
    appId: '1:1083009137937:android:0d1645719753a8cef520b0',
    messagingSenderId: '1083009137937',
    projectId: 'flutterauthentication-ae1d0',
    storageBucket: 'flutterauthentication-ae1d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlIVsG-Sw-jhh0SIefkTP9xgt7dDy4pjQ',
    appId: '1:1083009137937:ios:0c1ae770bc31216cf520b0',
    messagingSenderId: '1083009137937',
    projectId: 'flutterauthentication-ae1d0',
    storageBucket: 'flutterauthentication-ae1d0.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlIVsG-Sw-jhh0SIefkTP9xgt7dDy4pjQ',
    appId: '1:1083009137937:ios:0c1ae770bc31216cf520b0',
    messagingSenderId: '1083009137937',
    projectId: 'flutterauthentication-ae1d0',
    storageBucket: 'flutterauthentication-ae1d0.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC22oNgNbYqUu3ldzduehMmQ2t3dS5ZHt4',
    appId: '1:1083009137937:web:2c992d48b5959938f520b0',
    messagingSenderId: '1083009137937',
    projectId: 'flutterauthentication-ae1d0',
    authDomain: 'flutterauthentication-ae1d0.firebaseapp.com',
    storageBucket: 'flutterauthentication-ae1d0.firebasestorage.app',
  );
}
